---
version: "2"
plugins:
  csslint:
    enabled: true
    checks:
      box-sizing:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
  eslint:
    enabled: false
    channel: "eslint-7"
    config:
      config: .eslintrc.yml
  fixme:
    enabled: true
