---
version: "2"
plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
  eslint:
    enabled: false
    channel: "eslint-7"
    config:
      config: .eslintrc.yml
  fixme:
    enabled: true
