version = 1

exclude_patterns = [
  "dist/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["jquery"]
  globals = [
    "$state",
    "DataTable",
    "defineCalfPath",
    "defineCalfVer",
    "defineDataTablesPath",
    "defineEnvironment",
    "defineUserIsDev",
    "defineVersion",
    "GameController",
    "GameData",
    "gtag",
  ]