version = 1

exclude_patterns = [
  "dist/**"
]

[[analyzers]]
name = "javascript"
enabled = true
environment = ["jquery"]
globals = [
  "DataTable",
  "defineCalfPath",
  "defineCalfVer",
  "defineDataTablesPath",
  "defineEnvironment",
  "defineUserIsDev",
  "defineVersion",
  "GameController",
  "GameData",
  "gtag",
]