---
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - 'svelte3'
overrides:
  - files:
    - '*.svelte'
    processor: 'svelte3/svelte3'
    rules:
      no-label-var: off
      import/first: off
      import/no-mutable-exports: off
      import/prefer-default-export: off
  - files:
    - "scripts/*.js"
    rules:
      import/extensions:
        - error
        - ignorePackages
        - js: always
      no-console: off
  - files:
    - "lws.config.js"
    rules:
      import/extensions:
        - error
        - ignorePackages
        - js: always
extends:
  - 'airbnb-base'
globals:
  Audio: readonly
  Blob: readonly
  clearTimeout: readonly
  console: readonly
  CSSContainerRule: readonly
  document: readonly
  Document: readonly
  DOMParser: readonly
  Element: readonly
  EventTarget: readonly
  FormData: readonly
  getComputedStyle: readonly
  HTMLTableElement: readonly
  Image: readonly
  localStorage: readonly
  MutationObserver: readonly
  navigator: readonly
  Node: readonly
  performance: readonly
  Promise: readonly
  requestAnimationFrame: readonly
  setTimeout: readonly
  URL: readonly
  window: readonly
  XPathResult: readonly
  require: readonly
  '$': readonly
  jQuery: readonly
  GM_info: readonly
  ga: readonly
  GameController: readonly
  GameData: readonly
  RadioNodeList: readonly
  gtag: readonly
rules:
  consistent-return: off # 74
  import/no-extraneous-dependencies:
    - error
    - packageDir: './'
  import/no-unresolved:
    - error
    - ignore:
      - '_CALFJS'
  import/order:
    - error
    - alphabetize:
        order: asc
        caseInsensitive: true
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-restricted-syntax: off # 2
  no-underscore-dangle:
    - error
    - allow:
      - _allies
      - _enemies
      - _enhancements
      - _saveState
      - _showPage
      - _skills
