ruby:
  enabled: false

coffeescript:
  enabled: false

jshint:
  enabled: false

scss:
  enabled: false

haml:
  enabled: false

go:
  enabled: false

swift:
  enabled: false

eslint:
  enabled: true
  config_file: .eslintrc.yml
  ignore_file: .eslintignore
  version: 7.7.0
